# Config file for automatic testing at travis-ci.org

language: python

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=style
  - TOXENV=docs

install: 
  - pip install tox

script:
  - tox
